spring:
  mail:
    host: smtphz.qiye.163.com
    username: no-reply@zhihui02.ntesmail.com
    password: 3f1fa4a881A
    port: 25
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhihui?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 8d41e114c69a6ebe53d5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  type-aliases-package: zhihui.backend.pojo
random-utils:
  sed: 1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ
  length: 4
redis:
  db: 2
  hostname: localhost
  password:
  port: 6379
email:
  enable: true
  expire-time: 5
  send-as: no-reply@zhihui02.ntesmail.com
file:
  image-path: '/zhihui/zhihui-image/'
  file-path: '/zhihui/zhihui-file/'
  video-path: '/zhihui/zhihui-video/'
rsa:
  private-key-file-path: '/zhihui/zhihui-keys/private.pem'
  public-key-file-path: '/zhihui/zhihui-keys/public.pem'
jwt-utils:
  key: "CHENPRIME"
  expire-time: 48